

from django.urls import path, include
from .views import ProductAdminViewSet, CategoryListView, ReviewViewSet, PublicProductViewSet, GenerateAIContentView, ProductRecommendationView, ProductInventoryInsightView
# from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers

# Admin Router
admin_router = routers.DefaultRouter()
admin_router.register(r'manage', ProductAdminViewSet, basename='product-admin')

# Public & Nested Routers
router = routers.SimpleRouter()
router.register(r'', PublicProductViewSet, basename='products')

reviews_router = routers.NestedSimpleRouter(router, r'', lookup='product')
reviews_router.register(r'reviews', ReviewViewSet, basename='product-reviews')


urlpatterns = [
    # THE FIX: Move specific paths BEFORE generic paths that might also match.
    # The 'categories/' path is more specific than the '<pk>/' path generated by the router.
    path('categories/', CategoryListView.as_view(), name='category-list'),
    
    # Admin-specific URLs should also come before the generic ones.
    path('admin/', include(admin_router.urls)),
    path('admin/generate-content/', GenerateAIContentView.as_view(), name='generate-ai-content'),
    path('admin/inventory-insights/', ProductInventoryInsightView.as_view(), name='inventory-insights'),
    
    # The generic product recommendations path with a variable <pk>
    path('<int:pk>/recommendations/', ProductRecommendationView.as_view(), name='product-recommendations'),

    # Now, include the generic router URLs. These will handle '/api/products/' and '/api/products/<pk>/'.
    # Because 'categories/' was handled above, it won't be incorrectly captured here.
    path('', include(router.urls)),
    path('', include(reviews_router.urls)),
]

