# Generated by Django 5.2.5 on 2025-09-06 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='status',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 6, 6, 50, 6, 395343, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='qa_documents/'),
        ),
    ]
