# Generated by Django 5.2.5 on 2025-09-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_from_ai',
            field=models.BooleanField(default=False),
        ),
    ]
