# Generated by Django 5.2.5 on 2025-08-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated description.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_keywords',
            field=models.TextField(blank=True, help_text='AI-generated SEO keywords, comma-separated.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_meta_description',
            field=models.TextField(blank=True, help_text='AI-generated SEO meta description.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_meta_title',
            field=models.CharField(blank=True, help_text='AI-generated SEO meta title.', max_length=255, null=True),
        ),
    ]
