# Generated by Django 5.2.5 on 2025-08-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ai_description_product_ai_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ai_description',
        ),
    ]
