# Generated by Django 5.2.5 on 2025-08-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_tags',
            field=models.TextField(blank=True, help_text='AI-generated tags for recommendations, comma-separated.', null=True),
        ),
    ]
