# Generated by Django 5.2.5 on 2025-09-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_ai_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image file.', null=True, upload_to='products/'),
        ),
    ]
